splited shell conf

diff --git a/roles/bash/files/bashrc b/roles/bash/files/bashrc
--- a/roles/bash/files/bashrc
+++ b/roles/bash/files/bashrc
@@ -2,12 +2,10 @@
 # SECURITY{{{
 # don't run interactively
 [ -z "$PS1" ] && return
-# }}}
-# BYOBU {{{
-byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true
-# }}}
-# SETTINGS {{{
-PS1='\[\033[02;91m\]\u \[\033[01;00m\]at\[\033[02;92m\] \h \[\033[01;00m\]in\[\033[02;94m\] \W\[\033[01;00m\] \$ '
+# don't run in emacs editor
+if [ -z "$EMACS" ]; then
+    byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true
+fi
 # }}}
 # OPTIONS {{{
 # extended pattern matching
@@ -27,7 +25,20 @@ shopt -s globstar
 # append to the history file, don't overwrite it
 shopt -s histappend
 # }}}
-# COMPLETIONS {{{
+# ADDONS {{{
+# sudo hint
+if [ ! -e "$HOME/.sudo_as_admin_successful" ] && [ ! -e "$HOME/.hushlogin" ] ; then
+    case " $(groups) " in *\ admin\ *|*\ sudo\ *)
+    if [ -x /usr/bin/sudo ]; then
+	cat <<-EOF
+	To run a command as administrator (user "root"), use "sudo <command>".
+	See "man sudo_root" for details.
+	
+	EOF
+    fi
+    esac
+fi
+# bash completion
 if ! shopt -oq posix; then
   if [ -f /usr/share/bash-completion/bash_completion ]; then
     . /usr/share/bash-completion/bash_completion
@@ -35,18 +46,20 @@ if ! shopt -oq posix; then
     . /etc/bash_completion
   fi
 fi
-# }}}
-# CONFIGURATIONS {{{
-if [ -f ~/.environ ]; then
-    . ~/.environ
-fi
-if [ -f ~/.aliases ]; then
-    . ~/.aliases
-fi
-if [ -f ~/.private ]; then
-    . ~/.private
-fi
-if [ -f ~/.display ]; then
-    . ~/.display
+# command not found
+if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
+	function command_not_found_handle {
+	        # check because c-n-f could've been removed in the meantime
+                if [ -x /usr/lib/command-not-found ]; then
+		   /usr/lib/command-not-found -- "$1"
+                   return $?
+                elif [ -x /usr/share/command-not-found/command-not-found ]; then
+		   /usr/share/command-not-found/command-not-found -- "$1"
+                   return $?
+		else
+		   printf "%s: command not found\n" "$1" >&2
+		   return 127
+		fi
+	}
 fi
 # }}}
